spring.application.name=MongoDBDemo
spring.data.mongodb.uri=mongodb+srv://<username>:<password>@cluster0.derxm.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0/mystudentlist
spring.data.mongodb.database=mystudentlist
